name: Deploy checkers

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and TypeScript
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust to the version you are using in your project

      - name: Install dependencies
        run: |
          npm ci
          npm install typescript # Install TypeScript as part of your dependencies

      - name: TypeScript checkers
        run: |
          npx tsc --noEmit

      - name: Run TypeScript type checking
        run: |
          npm run build

